spring:
  application:
    name: uaa-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: ""

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

server:
  port: 53020
  servlet:
    context-path: /uaa
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

logging:
  level:
    root: info
    org:
      springframework:
        web: info


#spring.http.encoding.enabled = true
#spring.http.encoding.charset = UTF-8
#spring.http.encoding.force = true
#server.tomcat.remote_ip_header = x-forwarded-for
#server.tomcat.protocol_header = x-forwarded-proto
#server.use-forward-headers = true
#server.servlet.context-path = /uaa
#
#spring.freemarker.enabled = true
#spring.freemarker.suffix = .html
#spring.freemarker.request-context-attribute = rc
#spring.freemarker.content-type = text/html
#spring.freemarker.charset = UTF-8
#spring.mvc.throw-exception-if-no-handler-found = true
#spring.resources.add-mappings = false

#spring.datasource.url = jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=UTF-8
#spring.datasource.username=root
#spring.datasource.password=""
#spring.datasource.driver-class-name = com.mysql.jdbc.Driver

#eureka.client.serviceUrl.defaultZone = http://localhost:53000/eureka/
#eureka.instance.preferIpAddress = true
#eureka.instance.instance-id = ${spring.application.name}:${spring.cloud.client.ip-address}:${spring.application.instance_id:${server.port}}
#management.endpoints.web.exposure.include = refresh,health,info,env
#
#feign.hystrix.enabled = true
#feign.compression.request.enabled = true
#feign.compression.request.mime-types[0] = text/xml
#feign.compression.request.mime-types[1] = application/xml
#feign.compression.request.mime-types[2] = application/json
#feign.compression.request.min-request-size = 2048
#feign.compression.response.enabled = true