spring:
  application:
    name: order-service
  main:
    allow-bean-definition-overriding: true
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/spring-security?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: ""

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true

server:
  port: 53021
  servlet:
    context-path: /order
  use-forward-headers: true
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto

logging:
  level:
    root: info
    org:
      springframework:
        web: info

#spring.application.name=order‐service
#server.port=53021
#spring.main.allow‐bean‐definition‐overriding = true
#
#logging.level.root=debug
#logging.level.org.springframework.web=debug
